# This is a basic workflow to help you get started with Actions

name: GitHub Actions Code Coverage

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v3
        
      - name: Create folder
        run: mkdir coverage.cobertura.xml
        
      - name: Multi-line script
        run: |
          echo 1. what is in this directory
          ls -a
          echo
          echo 2. Where is coberture
          locate --basename coverage/**/coverage.cobertura.xml

      # Runs a single command using the runners shell
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Runs a set of commands using the runners shell
      - name: GitHub Actions Build Maven project
        run: mvn clean install --file pom.xml
      
      - name: Copy Coverage To Predictable Location
        #run: cp coverage/**/coverage.cobertura.xml coverage.cobertura.xml
        run: cp $dir/*/coverage.cobertura.xml coverage.cobertura.xml
      
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.2.0
        with:
          filename: coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
